name: nightly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
    
env:
  macOS: 'platform=macOS'
  watchOS: 'generic/platform=watchOS Simulator'
  iOS: 'generic/platform=iOS Simulator'
  tvOS: 'generic/platform=tvOS Simulator'
  visionOS: 'generic/platform=visionOS Simulator'

jobs:
  test_hosting:
    strategy:
      matrix:
        xcode-version: ['latest-stable']
        platform: [macOS, iOS, tvOS, watchOS]

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode-version }}

    - name: Testing ${{ matrix.platform }}
      run: |
        xcodebuild test \
          -scheme ViewHosting \
          -destination '${{ env[matrix.platform] }}' \
          -resultBundlePath TestResults.xcresult

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
        show-passed-tests: false
      if: failure()
      