name: nightly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
    
env:
  macOS: 'platform=macOS'
  watchOS: 'platform=watchOS Simulator,name=Apple Watch Ultra 2 (49mm)'
  iOS: 'platform=iOS Simulator,name=iPhone 15'
  tvOS: 'platform=tvOS Simulator,name=Apple TV'
  visionOS: 'platform=visionOS Simulator,name=Apple Vision Pro'

jobs:
  test_hosting:
    strategy:
      matrix:
        xcode-version: ['latest-stable', 'latest']
        platform: [macOS, iOS, tvOS, watchOS, visionOS]

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Cache Derived Data
      uses: actions/cache@v4
      with:
        path: ./DerivedData
        key: derived-data-${{ runner.os }}-${{ matrix.xcode-version }}-${{ matrix.platform }}-${{ hashFiles('**/Package.swift') }}

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode-version }}

    - name: Testing ${{ matrix.platform }}
      run: |
        xcodebuild test \
          -scheme ViewHosting-Package \
          -destination '${{ env[matrix.platform] }}' \
          -derivedDataPath ./DerivedData \
          -resultBundlePath TestResults.xcresult

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
        show-passed-tests: false
      if: failure()
      