name: nightly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *'
    
env:
  macOS: 'platform=macOS'
  watchOS: 'platform=watchOS Simulator,name=Apple Watch Series 10 (46mm)'
  iOS: 'platform=iOS Simulator,name=iPhone 16'
  tvOS: 'platform=tvOS Simulator,name=Apple TV'
  visionOS: 'platform=visionOS Simulator,name=Apple Vision Pro'

jobs:
  test_hosting:
    strategy:
      matrix:
        platform: [macOS, iOS, tvOS, watchOS, visionOS]

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Testing ${{ matrix.platform }}
      run: |
        xcodebuild test \
          -scheme ViewHosting-Package \
          -destination '${{ env[matrix.platform] }}' \
          -resultBundlePath TestResults.xcresult

    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: TestResults.xcresult
        show-passed-tests: false
      if: failure()
      